### ISSUE TITLE
Feature Request: Add support for custom namespace

### ISSUE THREAD

**Issue by brittonhayes** [micro/helm#3]
### Request

Hey there :wave: Love the project and the helm chart. Just wanted to see if you'd be open to adding the ability to enter a custom namespace.

### Current State

As of right now, all of the resources in the Helm template for micro are forced to go into the namespace `micro`. So I can't provide a custom namespace in helm.

### Example

e.g. The following doesn't deploy to `home`, it deploys to `micro` with a helm release in `home`. The expected result would be that this manifest would assign both the helm release and the resources associated with micro into the home namespace.

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: micro
  namespace: home
spec:
  releaseName: micro
  targetNamespace: home
  interval: 5m
  chart:
    spec:
      chart: micro
      version: v1.2.1
      sourceRef:
        kind: HelmRepository
        name: micro
        namespace: flux-system
      interval: 5m
  values:
    annotations:
      kubernetes.io/ingress.class: traefik
```

### Proposed Changes

> Wherever the following hard-coded string is present, replace with `{{.Release.Namespace}}`

```diff
-namespace: "micro"
+namespace: {{ .Release.Namespace }}
```
